default: &default
  adapter:  postgresql
  encoding: unicode
  host:     <%= ENV["DB_HOST"] %>
  user:     <%= ENV["DB_USER"] %>
  password: <%= ENV["DB_PASSWORD"] %>
  port:     <%= ENV["DB_PORT"] %>
  pool:     <%= ENV["POOL"] %>
  variables:
    statement_timeout:  <%= ENV["DB_STATEMENT_TIMEOUT"] %>
  sslmode: "require"

test:
  <<: *default
  host:     <%= ENV["LOCAL_DB_HOST"] %>
  database: <%= ENV["TEST_DB"] %>
  password: <%= ENV["LOCAL_DB_PASSWORD"] %>
  port:     <%= ENV["LOCAL_DB_PORT"] %>

development:
  <<: *default
  host:     <%= ENV['LOCAL_DB_HOST'] %>
  database: <%= ENV['DATABASE'] %>
  password: <%= ENV['LOCAL_DB_PASSWORD'] %>
  port:     <%= ENV['LOCAL_DB_PORT'] %>

production:
  <<: *default
  database: <%= ENV["DATABASE"] %>
